# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RASE' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RASE
  
    # Stripe Payments
    # pod 'Stripe'
    
    # Data Visualization
    pod 'Charts', '3.0.3'
    
    # Data Storage
    pod 'SQLite.swift', '~> 0.11.3'
    
    # XMPP Messaging
    # pod 'XMPPFramework', :git => "https://github.com/robbiehanson/XMPPFramework.git", :branch => 'master'
    # pod 'JSQMessagesViewController'
    
    # Amazon SDK Pods (Will delete uneeded)
    pod 'AWSAuthCore'
    pod 'AWSAPIGateway'
    pod 'AWSS3'
    pod 'AWSCognito'
    pod 'AWSCognitoIdentityProvider'
    
    # Gif Support for UIImage Views
    # pod 'SwiftGifOrigin', '~> 1.6.1'

  target 'RASETests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RASEUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
